### PR TITLE
Bump linux build from 14.04 to 18.04 to match windows build

### PR DESCRIPTION
**Pull request by RyanHir**
Bump Linux build to Ubuntu 18.04 to have a shared Dockerfile for both Linux and Windows builds, as well to become no longer dependent on a EOL distro.

This would make the official glibc requirment 2.27 as seen [here](https://packages.ubuntu.com/source/bionic/glibc) and the README had been updated to reflect this, but should still be compatible with older versions.

Tested on Debian Buster.

### CODE REVIEW

**Comment by ThadHouse** [comment]
We actually don't want to do this. We want to keep the 14.04 build, not just to be compatible with more version of ubuntu, but more versions of linux in general. Any specific reason you have to want to do this?

**Comment by RyanHir** [comment]
I was wishing to look into adding the rust compiler and toolchain for opening the door for C replacement in allwpilib but that is a long shot TBH. And using a supported distro would make things easier IMO.

And from my understanding of the linker and libc, the glibc compatibility only matters for compiling and the binaries it produces will link to the system. Sure there is the odd system running a legacy version of glibc but it should be mostly backwards compatible.

**Comment by RyanHir** [comment]
But if binary compatibility is the main issue, perhaps it is worth looking into near EOL (but supported) versions of CentOS such as CentOS 6 (EOL 2020-11-30) as it runs glibc 2.12, or CentOS 7 (EOL 2024-06-30) with glibc 2.17.

I apologize if this sounded a bit blunt but IMO, using a supported distro is probably the best choice for repo compatibility as the 14.04 repos will not always be around

**Comment by ThadHouse** [comment]
Rust mostly uses llvm iirc anyway, so going newer here probably wouldn't help too much. 

As for updating, docker makes it safer to use older OS versions, and we explicitly want to link to an older version of libc. Repos from ~2008 are still up, so I feel like 14.04 will stay up for a while, and we'd prefer not to change what is working well already.

**Comment by RyanHir** [comment]
That is understandable, I did not know about 2008 repos still running.

I just have one last thing to say that I just found. It looks like gcc and friends in the 18.04 container actually uses a mix of glibc symbol versions internally

```sh
ryan@think:~/devel/roborio-toolchain$ readelf -Ws frc2020/roborio/bin/* | grep GLIBC | awk '{print $8}' | sed 's/.*@//g' | sort | uniq
GLIBC_2.11
GLIBC_2.14
GLIBC_2.15
GLIBC_2.17
GLIBC_2.2.5
GLIBC_2.27
GLIBC_2.3
GLIBC_2.3.3
GLIBC_2.3.4
GLIBC_2.4
GLIBC_2.7
GLIBC_2.8
GLIBC_2.9
```

The command I am running is going through each x86_64 binary and returning their respective glibc symbol and it appears at some point, it does go to 2.27, so for now, it is probably not ideal like you said to merge.

I will leave this pull request open for a future date for if(or when) you all do wish to upgrade to 18.04 such as when most common desktop distros drop the older glibc

**Pull request closed without merging**
